before_script:
        - composer install --dev

stages:
        - build
        - deploy

build_doc:
        stage: build
        only:
                - master
        script:
                - 'make doc'
        artifacts:
                paths: 
                        - doc/doxygen/

deploy_doc:
        stage: deploy
        only:
                - master
        dependencies:
                - build_doc
        script:
                - '[ -n "$DOC_INSTALL_DESTINATION" ] && rsync "./doc/doxygen/html/" "$DOC_INSTALL_DESTINATION/"'

